import '../../../core/assets/assets.gen.dart';
import 'favourite_product_model.dart';

final List<FavouriteProductModel> mockFavouriteProducts = [
  FavouriteProductModel(
    id: '1',
    name: 'Nintendo Switch OLED',
    imageUrl: "https://cdn.xtmobile.vn/vnt_upload/product/11_2023/thumbs/600_14_pro_3_e7b3f3781add4f398951c3b.jpg",
    price: 8500000,
    category: 'Xiaomi',
    brand: 'Nintendo',
    series: 'Switch',
    timeAgo: '1 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),

  FavouriteProductModel(
    id: '1',
    name: 'Nintendo Switch OLED',
    imageUrl: "https://cdn.xtmobile.vn/vnt_upload/product/02_2024/thumbs/600_xiaomi_14_ultra_den_xtmobile.jpg",
    price: 8500000,
    category: 'Xiaomi',
    brand: 'Nintendo',
    series: 'Switch',
    timeAgo: '1 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),

  FavouriteProductModel(
    id: '3',
    name: 'Nintendo Switch Lite',
    imageUrl: "https://chiemtaimobile.vn/images/thumbnails/600/600/detailed/57/sung-massage-cam-tay-mini-xiaomi-3-mjjmq07ym.jpg",
    price: 6500000,
    category: 'Xiaomi',
    brand: 'Nintendo',
    series: 'Lite',
    timeAgo: '5 giờ trước',
    imgBrand: Assets.images.logosFacebook.path,
  ),
  FavouriteProductModel(
    id: '4',
    name: 'Nintendo Switch Lite',
    imageUrl: "https://chiemtaimobile.vn/images/thumbnails/600/600/detailed/55/bo-sac-nhanh-100w-xiaomi-mdy-16-el-h1.jpg",
    price: 6500000,
    category: 'Xiaomi',
    brand: 'Xiaomi',
    series: 'Lite',
    timeAgo: '5 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: '5',
    name: 'Nintendo Switch Lite',
    imageUrl: Assets.images.bear1.path,
    price: 6500000,
    category: 'Xiaomi',
    brand: 'Xiaomi',
    series: 'Lite',
    timeAgo: '5 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: '5',
    name: 'Nintendo Switch Lite',
    imageUrl: Assets.images.bear1.path,
    price: 6500000,
    category: 'Xiaomi',
    brand: 'Xiaomi',
    series: 'Lite',
    timeAgo: '5 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: '5',
    name: 'Nintendo Switch Lite',
    imageUrl: Assets.images.bear1.path,
    price: 6500000,
    category: 'Xiaomi',
    brand: 'Xiaomi',
    series: 'Lite',
    timeAgo: '5 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: '5',
    name: 'Nintendo Switch Lite',
    imageUrl: Assets.images.bear1.path,
    price: 6500000,
    category: 'Xiaomi',
    brand: 'Xiaomi',
    series: 'Lite',
    timeAgo: '5 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: '2',
    name: 'Apple Watch S9',
    imageUrl: "https://cdn.xtmobile.vn/vnt_upload/product/10_2024/thumbs/600_Xiaomi_redmi_note_14_mau_den_xtmobile.jpg",
    price: 10500000,
    category: 'Đồng hồ thông minh',
    brand: 'Apple',
    series: 'Series 9',
    timeAgo: '3 giờ trước',
    imgBrand: Assets.images.logosFacebook.path,
  ),
  FavouriteProductModel(
    id: '2',
    name: 'Apple Watch S9',
    imageUrl: Assets.images.bear1.path,
    price: 10500000,
    category: 'Đồng hồ thông minh',
    brand: 'Apple',
    series: 'Series 9',
    timeAgo: '3 giờ trước',
    imgBrand: Assets.images.logosFacebook.path,
  ),
  FavouriteProductModel(
    id: '1',
    name: 'Nintendo Switch OLED',
    imageUrl: "https://cdn.xtmobile.vn/vnt_upload/product/02_2025/thumbs/600_xiaomi_15_ultra.jpg",
    price: 8500000,
    category: 'Xiaomi',
    brand: 'Nintendo',
    series: 'Switch',
    timeAgo: '1 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: '2',
    name: 'Apple Watch S9',
    imageUrl: "https://cdn.xtmobile.vn/vnt_upload/product/11_2024/thumbs/600_xiaomi_15_pro_mau_xanh_la_xtmobile_2.jpg",
    price: 10500000,
    category: 'Đồng hồ thông minh',
    brand: 'Apple',
    series: 'Series 9',
    timeAgo: '3 giờ trước',
    imgBrand: Assets.images.logosFacebook.path,
  ),
];

final List<FavouriteProductModel> popularSuggestions = [
  FavouriteProductModel(
    id: 'p01',
    name: 'iPhone 16 Pro Max',
    imageUrl: Assets.images.bear1.path,
    price: 46990000,
    category: 'Apple',
    brand: 'Apple',
    series: 'iPhone',
    timeAgo: '1 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: 'p02',
    name: 'Samsung Galaxy S24 Ultra',
    imageUrl: Assets.images.bear1.path,
    price: 32990000,
    category: 'Samsung',
    brand: 'Samsung',
    series: 'Galaxy S',
    timeAgo: '3 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: 'p03',
    name: 'Xiaomi 14 Pro',
    imageUrl: Assets.images.bear1.path,
    price: 18990000,
    category: 'Xiaomi',
    brand: 'Xiaomi',
    series: 'Mi Series',
    timeAgo: '5 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: 'p04',
    name: 'OPPO Find X7',
    imageUrl: Assets.images.bear1.path,
    price: 15990000,
    category: 'Oppo',
    brand: 'Oppo',
    series: 'Find X',
    timeAgo: '6 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: 'p04',
    name: 'OPPO Find X7',
    imageUrl: Assets.images.bear1.path,
    price: 15990000,
    category: 'Oppo',
    brand: 'Oppo',
    series: 'Find X',
    timeAgo: '6 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: 'p04',
    name: 'OPPO Find X7',
    imageUrl: "https://cdn.xtmobile.vn/vnt_upload/product/08_2019/thumbs/600_xiaomi-redmi-note-10s-xtmobile_1.jpg",
    price: 15990000,
    category: 'Oppo',
    brand: 'Oppo',
    series: 'Find X',
    timeAgo: '6 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: 'p04',
    name: 'OPPO Find X7',
    imageUrl: Assets.images.bear1.path,
    price: 15990000,
    category: 'Oppo',
    brand: 'Oppo',
    series: 'Find X',
    timeAgo: '6 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  FavouriteProductModel(
    id: 'p04',
    name: 'OPPO Find X7',
    imageUrl: Assets.images.bear1.path,
    price: 15990000,
    category: 'Oppo',
    brand: 'Oppo',
    series: 'Find X',
    timeAgo: '6 giờ trước',
    imgBrand: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
];
