import 'package:fido_box_demo01/modules/favourite/domain/saved_product_model.dart';

final List<SavedProductModel> mockSavedProducts = [
  SavedProductModel(
    id: "1",
    name: "Iphone 15 Promax",
    imageUrl: "https://cdn.xtmobile.vn/vnt_upload/product/11_2023/thumbs/600_14_pro_3_e7b3f3781add4f398951c3b.jpg",
    price: 30000000,
    discountAmount: 320000,
    conditionLabel: "99%",
    screenStatus: "Màn hình bình thường",
    scratchStatus: "Không trầy xước",
    tag: "Top 1 điện thoại bán chạy nhất",
    sellerName: "Lao Hoang Minh Tam",
    sellerAvatar: "https://logospng.org/wp-content/uploads/xiaomi.png",
  ),
  SavedProductModel(
    id: "2",
    name: "Iphone 15 Promax",
    imageUrl: "https://cdn.xtmobile.vn/vnt_upload/product/11_2023/thumbs/600_14_pro_3_e7b3f3781add4f398951c3b.jpg",
    price: 30000000,
    discountAmount: 320000,
    conditionLabel: "99%",
    screenStatus: "Màn hình bình thường",
    scratchStatus: "Không trầy xước",
    tag: "Top 1 điện thoại bán chạy nhất",
    sellerName: "XiaoYu",
    sellerAvatar: "https://logospng.org/wp-content/uploads/xiaomi.png",
    isOutOfStock: true,
  ), SavedProductModel(
    id: "3",
    name: "Iphone 15 Promax",
    imageUrl: "https://cdn.xtmobile.vn/vnt_upload/product/11_2023/thumbs/600_14_pro_3_e7b3f3781add4f398951c3b.jpg",
    price: 30000000,
    discountAmount: 320000,
    conditionLabel: "99%",
    screenStatus: "Màn hình bình thường",
    scratchStatus: "Không trầy xước",
    tag: "Top 1 điện thoại bán chạy nhất",
    sellerName: "XiaoYu",
    sellerAvatar: "https://logospng.org/wp-content/uploads/xiaomi.png",
    isOutOfStock: true,
  ), SavedProductModel(
    id: "4",
    name: "Iphone 15 Promax",
    imageUrl: "https://cdn.xtmobile.vn/vnt_upload/product/11_2023/thumbs/600_14_pro_3_e7b3f3781add4f398951c3b.jpg",
    price: 30000000,
    discountAmount: 320000,
    conditionLabel: "99%",
    screenStatus: "Màn hình bình thường",
    scratchStatus: "Không trầy xước",
    tag: "Top 1 điện thoại bán chạy nhất",
    sellerName: "XiaoYu",
    sellerAvatar: "https://logospng.org/wp-content/uploads/xiaomi.png",
    isOutOfStock: true,
  ), SavedProductModel(
    id: "5",
    name: "Iphone 15 Promax",
    imageUrl: "https://cdn.xtmobile.vn/vnt_upload/product/11_2023/thumbs/600_14_pro_3_e7b3f3781add4f398951c3b.jpg",
    price: 30000000,
    discountAmount: 320000,
    conditionLabel: "99%",
    screenStatus: "Màn hình bình thường",
    scratchStatus: "Không trầy xước",
    tag: "Top 1 điện thoại bán chạy nhất",
    sellerName: "XiaoYu",
    sellerAvatar: "https://logospng.org/wp-content/uploads/xiaomi.png",
    isOutOfStock: true,
  ),
];
