import 'package:fido_box_demo01/core/assets/locale_keys.g.dart';
import 'package:fido_box_demo01/core/extensions/string_extension.dart';
import 'store_model.dart';

final List<StoreModel> mockStores = [
  StoreModel(
    id: '1',
    name: LocaleKeys.store_1_name.trans(),
    description: LocaleKeys.store_1_description.trans(),
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400',
    latitude: 10.762622,
    longitude: 106.660172,
    openHours: '10:00 - 21:30',
    services: [
      LocaleKeys.service_phone.trans(),
      LocaleKeys.service_laptop.trans(),
      LocaleKeys.service_tablet.trans(),
      LocaleKeys.service_camera.trans(),
      LocaleKeys.service_smartwatch.trans(),
      LocaleKeys.service_headphone.trans(),
      LocaleKeys.service_console.trans(),
    ],
    categories: [
      LocaleKeys.category_phones.trans(),
      LocaleKeys.category_laptops.trans(),
      LocaleKeys.category_digital_devices.trans(),
    ],
    district: LocaleKeys.district_1.trans(),
  ),
  StoreModel(
    id: '2',
    name: LocaleKeys.store_2_name.trans(),
    description: LocaleKeys.store_2_description.trans(),
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400',
    latitude: 10.776889,
    longitude: 106.700806,
    openHours: '09:00 - 22:00',
    services: [
      LocaleKeys.service_phone.trans(),
      LocaleKeys.service_laptop.trans(),
      LocaleKeys.service_tablet.trans(),
      LocaleKeys.service_camera.trans(),
      LocaleKeys.service_smartwatch.trans(),
      LocaleKeys.service_headphone.trans(),
    ],
    categories: [
      LocaleKeys.category_phones.trans(),
      LocaleKeys.category_laptops.trans(),
      LocaleKeys.category_digital_devices.trans(),
    ],
    district: LocaleKeys.district_1.trans(),
  ),
  StoreModel(
    id: '3',
    name: LocaleKeys.store_3_name.trans(),
    description: LocaleKeys.store_3_description.trans(),
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400',
    latitude: 10.870000,
    longitude: 106.800000,
    openHours: '08:30 - 21:00',
    services: [
      LocaleKeys.service_phone.trans(),
      LocaleKeys.service_laptop.trans(),
      LocaleKeys.service_tablet.trans(),
      LocaleKeys.service_smartwatch.trans(),
    ],
    categories: [
      LocaleKeys.category_phones.trans(),
      LocaleKeys.category_laptops.trans(),
    ],
    district: LocaleKeys.district_thu_duc.trans(),
  ),
  StoreModel(
    id: '4',
    name: LocaleKeys.store_4_name.trans(),
    description: LocaleKeys.store_4_description.trans(),
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400',
    latitude: 10.801755,
    longitude: 106.710000,
    openHours: '10:00 - 21:30',
    services: [
      LocaleKeys.service_phone.trans(),
      LocaleKeys.service_laptop.trans(),
      LocaleKeys.service_camera.trans(),
      LocaleKeys.service_headphone.trans(),
      LocaleKeys.service_console.trans(),
    ],
    categories: [
      LocaleKeys.category_phones.trans(),
      LocaleKeys.category_laptops.trans(),
      LocaleKeys.category_digital_devices.trans(),
    ],
    district: LocaleKeys.district_binh_thanh.trans(),
  ),
  StoreModel(
    id: '5',
    name: LocaleKeys.store_5_name.trans(),
    description: LocaleKeys.store_5_description.trans(),
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400',
    latitude: 10.800000,
    longitude: 106.650000,
    openHours: '09:30 - 22:00',
    services: [
      LocaleKeys.service_phone.trans(),
      LocaleKeys.service_laptop.trans(),
      LocaleKeys.service_tablet.trans(),
      LocaleKeys.service_camera.trans(),
    ],
    categories: [
      LocaleKeys.category_phones.trans(),
      LocaleKeys.category_laptops.trans(),
    ],
    district: LocaleKeys.district_tan_binh.trans(),
  ),
];
